name: Validate Atlas on Pull Request

on:
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate Atlas Markdown
        id: validate
        uses: pppdns/validate-atlas@v1  # or use @main for latest
        with:
          file_path: docs/atlas.md
        continue-on-error: true
      
      - name: Comment on PR
        if: steps.validate.outputs.has_errors == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Atlas Markdown validation found errors. Please check the workflow logs and file annotations for details.'
            })
      
      - name: Fail if validation errors
        if: steps.validate.outputs.has_errors == 'true'
        run: exit 1

