name: Validate Atlas on Pull Request

on:
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required for posting comments
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate Atlas Markdown
        id: validate
        uses: pppdns/validate-atlas@main
        with:
          file_path: atlas.md
        continue-on-error: true
      
      - name: Post validation results to PR
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Read the validation summary file
            let summary = '';
            try {
              summary = fs.readFileSync('validation-summary.md', 'utf8');
            } catch (error) {
              summary = '## ⚠️ Validation Summary Not Available\n\nUnable to read validation results.';
            }
            
            // Post new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: summary
            });
      
      - name: Fail if validation errors
        if: steps.validate.outputs.has_errors == 'true'
        run: exit 1
